#!/bin/bash -eux
BASE_URL=https://raw.githubusercontent.com/jorgenschaefer/elpy/master
REQUIREMENTS_FILES=(requirements-dev.txt requirements.txt requirements3.txt)
main() {
    local requirement_file
    for requirement_file in "${REQUIREMENTS_FILES[@]}"; do
        wget "$BASE_URL/$requirement_file"
    done
}
main "$@"
