name: learn-github-actions
on:
  push:
  schedule:
    - cron: '5 7 * * *'
jobs:
  setup-emacs-build-environment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # We'd like to compare with previous run's package.list... however github actions do not allow this at this time
      # - run: ls -lR
      # - uses: actions/download-artifact@v2
      # - run: ls -lR
      # - run: mv -v package.list package.list.prev || true
      - id: version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.version.outputs.version-without-v }}
      - run: sudo ./prepare.sh
      - run: make package.list
      # - run: diff -urwpN package.list.prev package.list > package.diff || true
      - uses: actions/upload-artifact@v2
        with:
          name: package-list
          path: |
            package.list
