name: learn-github-actions
on:
  push:
  schedule:
    - cron: '5 7 * * *'
jobs:
  setup-emacs-build-environment:
    runs-on: ubuntu-20.04
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - run: ls -lR | tee ls.txt; touch package.list package.diff foo
      # - run: mkdir -p prev-package-list && touch prev-package-list/package.list
      # - run: sudo ./prepare.sh
      # - run: make package.list
      # - if: always()
      #   run: |
      #     diff -urwp prev-package-list/package.list package.list > package.diff
      - uses: actions/upload-artifact@v2
        with:
          name: package-list
          path: |
            ls.txt
            package.*
