name: learn-github-actions
on: [push]
jobs:
  setup-emacs-build-environment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo ./prepare.sh
      - run: make package
