name: Build and Upload Release Asset
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build and Upload Release Asset
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: build
        run: |
          set -eux
          sudo ./prepare.sh
          make package
      - id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./build/emacsd.zip
          asset_name: emacsd-${{ github.ref }}.zip
          asset_content_type: application/zip
